// Census data for different years
export const censusData = {
  2021: {
    year: 2021,
    bsYear: '2078',
    label: 'Census 2021 (2078 BS)',
    general: {
      location: 'Wards 3, 4 & 5, Siraha Municipality',
      province: 'Madhesh',
      area: '300–600 hectares (est.)',
      population: '20,000–25,000',
      households: '4,000–5,000',
      avgHouseholdSize: '~5 persons',
      populationDensity: '4,000–6,000 per sq. km (est.)',
      elevation: '80–100m above sea level',
    },
    demographics: {
      male: 48.5,
      female: 51.5,
      sexRatio: 95,
      age0_14: 33,
      age15_59: 58,
      age60plus: 9,
      growthRate: 1.35,
    },
    education: {
      literacyRate: 63,
      maleLiteracy: 73,
      femaleLiteracy: 54,
      governmentSchools: 3,
      privateSchools: 2,
      madrasas: 6,
      higherSecondary: true,
      enrollmentRate: 82,
      dropoutRate: 12,
      madrasaStudents: 45,
      schoolStudents: 55,
      femaleEnrollment: 48,
      maleEnrollment: 52,
    },
    economy: {
      foreignEmployment: 65,
      business: 15,
      informalLabor: 10,
      agriculture: 10,
    },
    infrastructure: {
      electricity: 100,
      drinkingWater: 100,
      roadAccess: 80,
      internetAccess: 100,
      healthPosts: 2,
    },
    health: {
      toiletCoverage: 98,
      childVaccination: 99,
      maternalHealthAccess: 90,
      nearestHospitalKm: 1.6,
      birthAttendedByProfessional: 90,
      underFiveMortality: 28,
    },
    migration: {
      totalMigrants: 4500,
      destinations: [
        { country: 'Saudi Arabia', pct: 35 },
        { country: 'Qatar', pct: 20 },
        { country: 'UAE', pct: 15 },
        { country: 'Malaysia', pct: 15 },
        { country: 'India', pct: 10 },
        { country: 'Others', pct: 5 },
      ],
      estimatedRemittanceNPR: '500M–700M',
      remittanceDependency: 65,
    },
    languages: [
      { name: 'Local Ramaul', pct: 60 },
      { name: 'Maithili', pct: 25 },
      { name: 'Hindi', pct: 10 },
      { name: 'Urdu', pct: 5 },
    ],
    religions: [
      { name: 'Islam', pct: 85 },
      { name: 'Hinduism', pct: 14 },
      { name: 'Others', pct: 1 },
    ],
    festivals: ['Eid-ul-Fitr', 'Eid-ul-Azha', 'Shab-e-Barat', 'Milad-un-Nabi', 'Muharram', 'Chhath Puja', 'Diwali', 'Holi', 'Dashain', 'Tihar'],
  },
  2011: {
    year: 2011,
    bsYear: '2068',
    label: 'Census 2011 (2068 BS)',
    general: {
      location: 'Wards 3, 4 & 5, Siraha Municipality',
      province: 'Madhesh (formerly Sagarmatha Zone)',
      area: '300–600 hectares (est.)',
      population: '8,000–10,000',
      households: '1,800–2,200',
      avgHouseholdSize: '~5.5 persons',
      populationDensity: '2,000–3,000 per sq. km (est.)',
      elevation: '80–100m above sea level',
    },
    demographics: {
      male: 49.5,
      female: 50.5,
      sexRatio: 98,
      age0_14: 38,
      age15_59: 52,
      age60plus: 10,
      growthRate: 1.6,
    },
    education: {
      literacyRate: 48,
      maleLiteracy: 60,
      femaleLiteracy: 36,
      governmentSchools: 2,
      privateSchools: 1,
      madrasas: 4,
      higherSecondary: false,
      enrollmentRate: 65,
      dropoutRate: 22,
      madrasaStudents: 55,
      schoolStudents: 45,
      femaleEnrollment: 40,
      maleEnrollment: 60,
    },
    economy: {
      foreignEmployment: 25,
      business: 15,
      informalLabor: 15,
      agriculture: 45,
    },
    infrastructure: {
      electricity: 65,
      drinkingWater: 55,
      roadAccess: 35,
      internetAccess: 10,
      healthPosts: 1,
    },
    health: {
      toiletCoverage: 45,
      childVaccination: 55,
      maternalHealthAccess: 40,
      nearestHospitalKm: 3,
      birthAttendedByProfessional: 30,
      underFiveMortality: 48,
    },
    migration: {
      totalMigrants: 1800,
      destinations: [
        { country: 'India', pct: 40 },
        { country: 'Saudi Arabia', pct: 25 },
        { country: 'Qatar', pct: 15 },
        { country: 'Malaysia', pct: 12 },
        { country: 'UAE', pct: 5 },
        { country: 'Others', pct: 3 },
      ],
      estimatedRemittanceNPR: '100M–150M',
      remittanceDependency: 40,
    },
    languages: [
      { name: 'Local Ramaul', pct: 55 },
      { name: 'Maithili', pct: 28 },
      { name: 'Hindi', pct: 12 },
      { name: 'Urdu', pct: 5 },
    ],
    religions: [
      { name: 'Islam', pct: 82 },
      { name: 'Hinduism', pct: 17 },
      { name: 'Others', pct: 1 },
    ],
    festivals: ['Eid-ul-Fitr', 'Eid-ul-Azha', 'Shab-e-Barat', 'Milad-un-Nabi', 'Chhath Puja', 'Diwali', 'Holi', 'Dashain'],
  },
  2001: {
    year: 2001,
    bsYear: '2058',
    label: 'Census 2001 (2058 BS)',
    general: {
      location: 'Wards 3, 4 & 5, Siraha Municipality area',
      province: 'Sagarmatha Zone (pre-federal)',
      area: '300–600 hectares (est.)',
      population: '5,000–6,000',
      households: '1,000–1,200',
      avgHouseholdSize: '~6 persons',
      populationDensity: '1,200–1,800 per sq. km (est.)',
      elevation: '80–100m above sea level',
    },
    demographics: {
      male: 50.5,
      female: 49.5,
      sexRatio: 102,
      age0_14: 42,
      age15_59: 49,
      age60plus: 9,
      growthRate: 2.1,
    },
    education: {
      literacyRate: 32,
      maleLiteracy: 45,
      femaleLiteracy: 18,
      governmentSchools: 1,
      privateSchools: 0,
      madrasas: 3,
      higherSecondary: false,
      enrollmentRate: 45,
      dropoutRate: 38,
      madrasaStudents: 65,
      schoolStudents: 35,
      femaleEnrollment: 30,
      maleEnrollment: 70,
    },
    economy: {
      foreignEmployment: 5,
      business: 5,
      informalLabor: 8,
      agriculture: 82,
    },
    infrastructure: {
      electricity: 30,
      drinkingWater: 25,
      roadAccess: 15,
      internetAccess: 0,
      healthPosts: 0,
    },
    health: {
      toiletCoverage: 15,
      childVaccination: 30,
      maternalHealthAccess: 15,
      nearestHospitalKm: 5,
      birthAttendedByProfessional: 10,
      underFiveMortality: 75,
    },
    migration: {
      totalMigrants: 300,
      destinations: [
        { country: 'India', pct: 70 },
        { country: 'Saudi Arabia', pct: 15 },
        { country: 'Qatar', pct: 5 },
        { country: 'Malaysia', pct: 5 },
        { country: 'UAE', pct: 3 },
        { country: 'Others', pct: 2 },
      ],
      estimatedRemittanceNPR: '10M–20M',
      remittanceDependency: 10,
    },
    languages: [
      { name: 'Local Ramaul', pct: 55 },
      { name: 'Maithili', pct: 32 },
      { name: 'Hindi', pct: 8 },
      { name: 'Urdu', pct: 5 },
    ],
    religions: [
      { name: 'Islam', pct: 80 },
      { name: 'Hinduism', pct: 19 },
      { name: 'Others', pct: 1 },
    ],
    festivals: ['Eid-ul-Fitr', 'Eid-ul-Azha', 'Shab-e-Barat', 'Chhath Puja', 'Diwali', 'Holi'],
  },
};

export const CHART_COLORS = [
  'hsl(152, 45%, 28%)', 'hsl(38, 85%, 50%)', 'hsl(220, 70%, 55%)',
  'hsl(0, 70%, 55%)', 'hsl(280, 60%, 55%)', 'hsl(180, 50%, 40%)',
];

export const populationGrowth = [
  { year: '1991', population: 5000 },
  { year: '2001', population: 5500 },
  { year: '2011', population: 9000 },
  { year: '2021', population: 22000 },
];

export const literacyComparison = [
  { year: '2001', total: 32, male: 45, female: 18 },
  { year: '2011', total: 48, male: 60, female: 36 },
  { year: '2021', total: 63, male: 73, female: 54 },
];

export const infrastructureComparison = [
  { metric: 'Electricity', '2001': 30, '2011': 65, '2021': 100 },
  { metric: 'Drinking Water', '2001': 25, '2011': 55, '2021': 100 },
  { metric: 'Road Access', '2001': 15, '2011': 35, '2021': 80 },
  { metric: 'Internet', '2001': 0, '2011': 10, '2021': 100 },
];

export const migrationGrowth = [
  { year: '2001', migrants: 300, remittancePct: 10 },
  { year: '2011', migrants: 1800, remittancePct: 40 },
  { year: '2021', migrants: 4500, remittancePct: 65 },
];

export const healthComparison = [
  { metric: 'Toilet Coverage', '2001': 15, '2011': 45, '2021': 98 },
  { metric: 'Vaccination', '2001': 30, '2011': 55, '2021': 99 },
  { metric: 'Maternal Access', '2001': 15, '2011': 40, '2021': 90 },
  { metric: 'Professional Birth', '2001': 10, '2011': 30, '2021': 90 },
];

export const enrollmentComparison = [
  { year: '2001', enrollment: 45, dropout: 38, femaleRate: 30 },
  { year: '2011', enrollment: 65, dropout: 22, femaleRate: 40 },
  { year: '2021', enrollment: 82, dropout: 12, femaleRate: 48 },
];

export type CensusYear = keyof typeof censusData;
